### ISSUE TITLE
Add T3-rtx timer and congestion control

### ISSUE THREAD

**Issue by kc5nra** [pion/sctp#11]
https://tools.ietf.org/html/rfc4960#section-6.3.3

**Comment by enobufs** [comment]
One consideration:
getPayloadDataToSend() method (will land on master soon) has time.Now() inside it. We should put it outside to make testing easier.

**Comment by kc5nra** [comment]
> One consideration:
> getPayloadDataToSend() method (will land on master soon) has time.Now() inside it. We should put it outside to make testing easier.

As well as time.Since

**Comment by enobufs** [comment]
I am going to start working on this issue form this weekend. The implementation would somewhat relate to congestion control, #14 and likely #21 would be addressed all together.

During the work of pions/webrtc#334, I ran a test with lossy connections using Network Link Conditioner. I noticed nearly 40% of the time, data channel establishment stalled (at 10% packet loss ration on both directions), which is due to the lack of INIT and COOKIE ECHO retransmissions.  This is very crucial for the real world use cases.  So, I am thinking about implementing those in this work as well.

Retransmission timers missing:
* T1-init timer
* T1-cookie timer
* T2-shutdown timer (note1)
* T3-rtx timer
* T5-shutdown-guard timer (note1)
* Heartbeat timer (note2)

> Note 1: this may be done after shutdown is fully implemented in a separat issue

> Note 2: this may be done after heartbeat is implemented in a separat issue

**Comment by enobufs** [comment]
I created a separate issue #24 for T1-init/cookie timers as I'd like to make these timers available earlier.

**Comment by enobufs** [comment]
Most implementation is done.  Now I am writing tests, which may take ~10 more hours. Once the tests are done, I will push my code for review.
Here's [my implementation note](https://docs.google.com/document/d/18HxKodWkPPfZpKTddQQvepux5MOS3QWMfK1eJYXQdz4/edit#)

**Comment by enobufs** [comment]
I have just realized that the `bufferredAmout` and its threshold are per-stream (per-datachannel) properties. I will need to update the code...

**Comment by enobufs** [comment]
We need to determine the size of the receive window size (rwnd), which is currently set to 64KB.
Initial ssthresh value is set to the rwnd as well (as recommended in RFC 4960)

From my quick research, Firefox and Chromium [used to have 128KB ](http://cse.aalto.fi/en/midcom-serveattachmentguid-1e5c98ab0819a0cc98a11e59ec1ad6153cbd4ebd4eb/eskola_webrtc.pdf)and both were [requested to increase it to 1MB](https://bugzilla.mozilla.org/show_bug.cgi?id=1051685) (not sure if that were accepted or not).

I guess 64KB is too small, and 128KB does not seem to be large enough over the modern Internet.  I guess we should bring it up to somewhere between 256KB and 1MB.

**Comment by enobufs** [comment]
Let's start with 128KB.  We will do more benchmark later and increase it as we become more confident about it.

**Comment by enobufs** [comment]
I found a bug in handleForwardTSN() sending SACK to every single FowardTSN. The SACK again generates ForwardTSN.

According to RFC 3758 Sec 3.6, SACK should only be sent when FowardTSN's newCumulativeTSN is the current peerLastTSN or behind.

I have locally confirmed that this fixed the "snowballing effect", and my stress test passed.

I will add the change to PR #26 soon.  (@Sean-Der)
