### ISSUE TITLE
Race condition for chunkmap access in payloadQueue

### ISSUE THREAD

**Issue by cohosh** [pion/sctp#114]
### Your environment.
  - Version: v1.7.5
  - Browser: N/A (Snowflake)
  - Other Information - see Tor ticket [#33211](https://trac.torproject.org/projects/tor/ticket/33211)

### What did you do?
There are more details in the ticket, but we found our application going into a CPU-intensive infinite loop. Profiling pointed us towards the `markAllToRetransmit` function in payload_queue.go: https://github.com/pion/sctp/blob/master/payload_queue.go#L163

I'm not sure whether the infinite loop behaviour we saw was due to this race condition but it seems plausible.

**Comment by enobufs** [comment]
@cohosh   Thanks for your report and the PR.
I recently fixed a bug (#109) that was causing 100% CPU usage which was fixed in v1.7.5. Looking at the Tor ticket #33211, at the very bottom, I see the identical logs reported in #109 and I am wondering if that has already been solved...

You reported above that your environment was pion/sctp v1.7.5 which is supposed to have the fix.  Could you please double-check if the Snowflake version experiencing the problem was actually using pion/sctp v1.7.5? (The last tag for pion/webrtc is v2.2.0 which still uses pion/sctp v1.7.4).

**Comment by Sean-Der** [comment]
Hey @cohosh @enobufs!

I tagged [v2.2.1](https://github.com/pion/webrtc/releases/tag/v2.2.1) I am working on profiling stuff (ICE performance) and coincidentally tagged it.

thanks!

**Comment by cohosh** [comment]
Hey @enobufs I think you're right. I wasn't actually able to reproduce the bug myself using the latest version. I'm guessing this is the issue. Thanks for that!

**Comment by enobufs** [comment]
@cohosh Let me close this case.  (If it happens with pion/sctp@v1.7.5, please reopen this.)
